apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: imdg-chatbot-server-root
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: imdg-chatbot
  sources:
    - repoURL: 'https://github.com/kelvin124/imdg-chatbot-argocd'
      targetRevision: main
      path: apps/imdg-chatbot/server
      directory:
        recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true