apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: infra
  sources:
    - repoURL: 'https://github.com/kelvin124/imdg-chatbot-argocd'
      targetRevision: main
      ref: current-repo  
    - chart: cert-manager
      repoURL: 'oci://quay.io/jetstack/charts/cert-manager'
      targetRevision: v1.20.2
      helm:
        valueFiles:
          - $current-repo/infrastructure/apps/cert-manager/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true